// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datatablesutils.proxies;

public class JoinedEntity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject joinedEntityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataTablesUtils.JoinedEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EntityName("EntityName"),
		EntityAlias("EntityAlias"),
		Path("Path"),
		JoinType("JoinType"),
		JoinOn("JoinOn"),
		JoinOrder("JoinOrder"),
		JoinedEntity_DataTablesView("DataTablesUtils.JoinedEntity_DataTablesView");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JoinedEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DataTablesUtils.JoinedEntity"));
	}

	protected JoinedEntity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject joinedEntityMendixObject)
	{
		if (joinedEntityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DataTablesUtils.JoinedEntity", joinedEntityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DataTablesUtils.JoinedEntity");

		this.joinedEntityMendixObject = joinedEntityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JoinedEntity.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static datatablesutils.proxies.JoinedEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datatablesutils.proxies.JoinedEntity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static datatablesutils.proxies.JoinedEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datatablesutils.proxies.JoinedEntity(context, mendixObject);
	}

	public static datatablesutils.proxies.JoinedEntity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datatablesutils.proxies.JoinedEntity.initialize(context, mendixObject);
	}

	public static java.util.List<datatablesutils.proxies.JoinedEntity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<datatablesutils.proxies.JoinedEntity> result = new java.util.ArrayList<datatablesutils.proxies.JoinedEntity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DataTablesUtils.JoinedEntity" + xpathConstraint))
			result.add(datatablesutils.proxies.JoinedEntity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of EntityName
	 */
	public final java.lang.String getEntityName()
	{
		return getEntityName(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityName
	 */
	public final java.lang.String getEntityName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EntityName.toString());
	}

	/**
	 * Set value of EntityName
	 * @param entityname
	 */
	public final void setEntityName(java.lang.String entityname)
	{
		setEntityName(getContext(), entityname);
	}

	/**
	 * Set value of EntityName
	 * @param context
	 * @param entityname
	 */
	public final void setEntityName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entityname)
	{
		getMendixObject().setValue(context, MemberNames.EntityName.toString(), entityname);
	}

	/**
	 * @return value of EntityAlias
	 */
	public final java.lang.String getEntityAlias()
	{
		return getEntityAlias(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityAlias
	 */
	public final java.lang.String getEntityAlias(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EntityAlias.toString());
	}

	/**
	 * Set value of EntityAlias
	 * @param entityalias
	 */
	public final void setEntityAlias(java.lang.String entityalias)
	{
		setEntityAlias(getContext(), entityalias);
	}

	/**
	 * Set value of EntityAlias
	 * @param context
	 * @param entityalias
	 */
	public final void setEntityAlias(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entityalias)
	{
		getMendixObject().setValue(context, MemberNames.EntityAlias.toString(), entityalias);
	}

	/**
	 * @return value of Path
	 */
	public final java.lang.String getPath()
	{
		return getPath(getContext());
	}

	/**
	 * @param context
	 * @return value of Path
	 */
	public final java.lang.String getPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Path.toString());
	}

	/**
	 * Set value of Path
	 * @param path
	 */
	public final void setPath(java.lang.String path)
	{
		setPath(getContext(), path);
	}

	/**
	 * Set value of Path
	 * @param context
	 * @param path
	 */
	public final void setPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String path)
	{
		getMendixObject().setValue(context, MemberNames.Path.toString(), path);
	}

	/**
	 * Set value of JoinType
	 * @param jointype
	 */
	public final datatablesutils.proxies.JoinType getJoinType()
	{
		return getJoinType(getContext());
	}

	/**
	 * @param context
	 * @return value of JoinType
	 */
	public final datatablesutils.proxies.JoinType getJoinType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.JoinType.toString());
		if (obj == null)
			return null;

		return datatablesutils.proxies.JoinType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of JoinType
	 * @param jointype
	 */
	public final void setJoinType(datatablesutils.proxies.JoinType jointype)
	{
		setJoinType(getContext(), jointype);
	}

	/**
	 * Set value of JoinType
	 * @param context
	 * @param jointype
	 */
	public final void setJoinType(com.mendix.systemwideinterfaces.core.IContext context, datatablesutils.proxies.JoinType jointype)
	{
		if (jointype != null)
			getMendixObject().setValue(context, MemberNames.JoinType.toString(), jointype.toString());
		else
			getMendixObject().setValue(context, MemberNames.JoinType.toString(), null);
	}

	/**
	 * @return value of JoinOn
	 */
	public final java.lang.String getJoinOn()
	{
		return getJoinOn(getContext());
	}

	/**
	 * @param context
	 * @return value of JoinOn
	 */
	public final java.lang.String getJoinOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JoinOn.toString());
	}

	/**
	 * Set value of JoinOn
	 * @param joinon
	 */
	public final void setJoinOn(java.lang.String joinon)
	{
		setJoinOn(getContext(), joinon);
	}

	/**
	 * Set value of JoinOn
	 * @param context
	 * @param joinon
	 */
	public final void setJoinOn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String joinon)
	{
		getMendixObject().setValue(context, MemberNames.JoinOn.toString(), joinon);
	}

	/**
	 * @return value of JoinOrder
	 */
	public final java.lang.Integer getJoinOrder()
	{
		return getJoinOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of JoinOrder
	 */
	public final java.lang.Integer getJoinOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.JoinOrder.toString());
	}

	/**
	 * Set value of JoinOrder
	 * @param joinorder
	 */
	public final void setJoinOrder(java.lang.Integer joinorder)
	{
		setJoinOrder(getContext(), joinorder);
	}

	/**
	 * Set value of JoinOrder
	 * @param context
	 * @param joinorder
	 */
	public final void setJoinOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer joinorder)
	{
		getMendixObject().setValue(context, MemberNames.JoinOrder.toString(), joinorder);
	}

	/**
	 * @return value of JoinedEntity_DataTablesView
	 */
	public final datatablesutils.proxies.DataTablesView getJoinedEntity_DataTablesView() throws com.mendix.core.CoreException
	{
		return getJoinedEntity_DataTablesView(getContext());
	}

	/**
	 * @param context
	 * @return value of JoinedEntity_DataTablesView
	 */
	public final datatablesutils.proxies.DataTablesView getJoinedEntity_DataTablesView(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		datatablesutils.proxies.DataTablesView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JoinedEntity_DataTablesView.toString());
		if (identifier != null)
			result = datatablesutils.proxies.DataTablesView.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JoinedEntity_DataTablesView
	 * @param joinedentity_datatablesview
	 */
	public final void setJoinedEntity_DataTablesView(datatablesutils.proxies.DataTablesView joinedentity_datatablesview)
	{
		setJoinedEntity_DataTablesView(getContext(), joinedentity_datatablesview);
	}

	/**
	 * Set value of JoinedEntity_DataTablesView
	 * @param context
	 * @param joinedentity_datatablesview
	 */
	public final void setJoinedEntity_DataTablesView(com.mendix.systemwideinterfaces.core.IContext context, datatablesutils.proxies.DataTablesView joinedentity_datatablesview)
	{
		if (joinedentity_datatablesview == null)
			getMendixObject().setValue(context, MemberNames.JoinedEntity_DataTablesView.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JoinedEntity_DataTablesView.toString(), joinedentity_datatablesview.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return joinedEntityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datatablesutils.proxies.JoinedEntity that = (datatablesutils.proxies.JoinedEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DataTablesUtils.JoinedEntity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
