// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datatablesutils.proxies;

public class XpathReference
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject xpathReferenceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataTablesUtils.XpathReference";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReferenceName("ReferenceName"),
		FromEntityName("FromEntityName"),
		ToEntityName("ToEntityName"),
		XpathSubView_XpathReference("DataTablesUtils.XpathSubView_XpathReference"),
		XpathReferenceNextLevel("DataTablesUtils.XpathReferenceNextLevel"),
		XpathReference_DataTablesView("DataTablesUtils.XpathReference_DataTablesView"),
		XpathReference_MxObjectReference("DataTablesUtils.XpathReference_MxObjectReference"),
		XpathReference_MxObjectType_From("DataTablesUtils.XpathReference_MxObjectType_From"),
		XpathReference_MxObjectType_To("DataTablesUtils.XpathReference_MxObjectType_To");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public XpathReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DataTablesUtils.XpathReference"));
	}

	protected XpathReference(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject xpathReferenceMendixObject)
	{
		if (xpathReferenceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DataTablesUtils.XpathReference", xpathReferenceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DataTablesUtils.XpathReference");

		this.xpathReferenceMendixObject = xpathReferenceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'XpathReference.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static datatablesutils.proxies.XpathReference initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datatablesutils.proxies.XpathReference.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static datatablesutils.proxies.XpathReference initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datatablesutils.proxies.XpathReference(context, mendixObject);
	}

	public static datatablesutils.proxies.XpathReference load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datatablesutils.proxies.XpathReference.initialize(context, mendixObject);
	}

	public static java.util.List<datatablesutils.proxies.XpathReference> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<datatablesutils.proxies.XpathReference> result = new java.util.ArrayList<datatablesutils.proxies.XpathReference>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DataTablesUtils.XpathReference" + xpathConstraint))
			result.add(datatablesutils.proxies.XpathReference.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ReferenceName
	 */
	public final java.lang.String getReferenceName()
	{
		return getReferenceName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceName
	 */
	public final java.lang.String getReferenceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReferenceName.toString());
	}

	/**
	 * Set value of ReferenceName
	 * @param referencename
	 */
	public final void setReferenceName(java.lang.String referencename)
	{
		setReferenceName(getContext(), referencename);
	}

	/**
	 * Set value of ReferenceName
	 * @param context
	 * @param referencename
	 */
	public final void setReferenceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String referencename)
	{
		getMendixObject().setValue(context, MemberNames.ReferenceName.toString(), referencename);
	}

	/**
	 * @return value of FromEntityName
	 */
	public final java.lang.String getFromEntityName()
	{
		return getFromEntityName(getContext());
	}

	/**
	 * @param context
	 * @return value of FromEntityName
	 */
	public final java.lang.String getFromEntityName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FromEntityName.toString());
	}

	/**
	 * Set value of FromEntityName
	 * @param fromentityname
	 */
	public final void setFromEntityName(java.lang.String fromentityname)
	{
		setFromEntityName(getContext(), fromentityname);
	}

	/**
	 * Set value of FromEntityName
	 * @param context
	 * @param fromentityname
	 */
	public final void setFromEntityName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fromentityname)
	{
		getMendixObject().setValue(context, MemberNames.FromEntityName.toString(), fromentityname);
	}

	/**
	 * @return value of ToEntityName
	 */
	public final java.lang.String getToEntityName()
	{
		return getToEntityName(getContext());
	}

	/**
	 * @param context
	 * @return value of ToEntityName
	 */
	public final java.lang.String getToEntityName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ToEntityName.toString());
	}

	/**
	 * Set value of ToEntityName
	 * @param toentityname
	 */
	public final void setToEntityName(java.lang.String toentityname)
	{
		setToEntityName(getContext(), toentityname);
	}

	/**
	 * Set value of ToEntityName
	 * @param context
	 * @param toentityname
	 */
	public final void setToEntityName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String toentityname)
	{
		getMendixObject().setValue(context, MemberNames.ToEntityName.toString(), toentityname);
	}

	/**
	 * @return value of XpathSubView_XpathReference
	 */
	public final datatablesutils.proxies.XpathSubView getXpathSubView_XpathReference() throws com.mendix.core.CoreException
	{
		return getXpathSubView_XpathReference(getContext());
	}

	/**
	 * @param context
	 * @return value of XpathSubView_XpathReference
	 */
	public final datatablesutils.proxies.XpathSubView getXpathSubView_XpathReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		datatablesutils.proxies.XpathSubView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.XpathSubView_XpathReference.toString());
		if (identifier != null)
			result = datatablesutils.proxies.XpathSubView.load(context, identifier);
		return result;
	}

	/**
	 * Set value of XpathSubView_XpathReference
	 * @param xpathsubview_xpathreference
	 */
	public final void setXpathSubView_XpathReference(datatablesutils.proxies.XpathSubView xpathsubview_xpathreference)
	{
		setXpathSubView_XpathReference(getContext(), xpathsubview_xpathreference);
	}

	/**
	 * Set value of XpathSubView_XpathReference
	 * @param context
	 * @param xpathsubview_xpathreference
	 */
	public final void setXpathSubView_XpathReference(com.mendix.systemwideinterfaces.core.IContext context, datatablesutils.proxies.XpathSubView xpathsubview_xpathreference)
	{
		if (xpathsubview_xpathreference == null)
			getMendixObject().setValue(context, MemberNames.XpathSubView_XpathReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.XpathSubView_XpathReference.toString(), xpathsubview_xpathreference.getMendixObject().getId());
	}

	/**
	 * @return value of XpathReferenceNextLevel
	 */
	public final datatablesutils.proxies.XpathReference getXpathReferenceNextLevel() throws com.mendix.core.CoreException
	{
		return getXpathReferenceNextLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of XpathReferenceNextLevel
	 */
	public final datatablesutils.proxies.XpathReference getXpathReferenceNextLevel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		datatablesutils.proxies.XpathReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.XpathReferenceNextLevel.toString());
		if (identifier != null)
			result = datatablesutils.proxies.XpathReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of XpathReferenceNextLevel
	 * @param xpathreferencenextlevel
	 */
	public final void setXpathReferenceNextLevel(datatablesutils.proxies.XpathReference xpathreferencenextlevel)
	{
		setXpathReferenceNextLevel(getContext(), xpathreferencenextlevel);
	}

	/**
	 * Set value of XpathReferenceNextLevel
	 * @param context
	 * @param xpathreferencenextlevel
	 */
	public final void setXpathReferenceNextLevel(com.mendix.systemwideinterfaces.core.IContext context, datatablesutils.proxies.XpathReference xpathreferencenextlevel)
	{
		if (xpathreferencenextlevel == null)
			getMendixObject().setValue(context, MemberNames.XpathReferenceNextLevel.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.XpathReferenceNextLevel.toString(), xpathreferencenextlevel.getMendixObject().getId());
	}

	/**
	 * @return value of XpathReference_DataTablesView
	 */
	public final datatablesutils.proxies.DataTablesView getXpathReference_DataTablesView() throws com.mendix.core.CoreException
	{
		return getXpathReference_DataTablesView(getContext());
	}

	/**
	 * @param context
	 * @return value of XpathReference_DataTablesView
	 */
	public final datatablesutils.proxies.DataTablesView getXpathReference_DataTablesView(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		datatablesutils.proxies.DataTablesView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.XpathReference_DataTablesView.toString());
		if (identifier != null)
			result = datatablesutils.proxies.DataTablesView.load(context, identifier);
		return result;
	}

	/**
	 * Set value of XpathReference_DataTablesView
	 * @param xpathreference_datatablesview
	 */
	public final void setXpathReference_DataTablesView(datatablesutils.proxies.DataTablesView xpathreference_datatablesview)
	{
		setXpathReference_DataTablesView(getContext(), xpathreference_datatablesview);
	}

	/**
	 * Set value of XpathReference_DataTablesView
	 * @param context
	 * @param xpathreference_datatablesview
	 */
	public final void setXpathReference_DataTablesView(com.mendix.systemwideinterfaces.core.IContext context, datatablesutils.proxies.DataTablesView xpathreference_datatablesview)
	{
		if (xpathreference_datatablesview == null)
			getMendixObject().setValue(context, MemberNames.XpathReference_DataTablesView.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.XpathReference_DataTablesView.toString(), xpathreference_datatablesview.getMendixObject().getId());
	}

	/**
	 * @return value of XpathReference_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getXpathReference_MxObjectReference() throws com.mendix.core.CoreException
	{
		return getXpathReference_MxObjectReference(getContext());
	}

	/**
	 * @param context
	 * @return value of XpathReference_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getXpathReference_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.XpathReference_MxObjectReference.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of XpathReference_MxObjectReference
	 * @param xpathreference_mxobjectreference
	 */
	public final void setXpathReference_MxObjectReference(mxmodelreflection.proxies.MxObjectReference xpathreference_mxobjectreference)
	{
		setXpathReference_MxObjectReference(getContext(), xpathreference_mxobjectreference);
	}

	/**
	 * Set value of XpathReference_MxObjectReference
	 * @param context
	 * @param xpathreference_mxobjectreference
	 */
	public final void setXpathReference_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectReference xpathreference_mxobjectreference)
	{
		if (xpathreference_mxobjectreference == null)
			getMendixObject().setValue(context, MemberNames.XpathReference_MxObjectReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.XpathReference_MxObjectReference.toString(), xpathreference_mxobjectreference.getMendixObject().getId());
	}

	/**
	 * @return value of XpathReference_MxObjectType_From
	 */
	public final mxmodelreflection.proxies.MxObjectType getXpathReference_MxObjectType_From() throws com.mendix.core.CoreException
	{
		return getXpathReference_MxObjectType_From(getContext());
	}

	/**
	 * @param context
	 * @return value of XpathReference_MxObjectType_From
	 */
	public final mxmodelreflection.proxies.MxObjectType getXpathReference_MxObjectType_From(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.XpathReference_MxObjectType_From.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of XpathReference_MxObjectType_From
	 * @param xpathreference_mxobjecttype_from
	 */
	public final void setXpathReference_MxObjectType_From(mxmodelreflection.proxies.MxObjectType xpathreference_mxobjecttype_from)
	{
		setXpathReference_MxObjectType_From(getContext(), xpathreference_mxobjecttype_from);
	}

	/**
	 * Set value of XpathReference_MxObjectType_From
	 * @param context
	 * @param xpathreference_mxobjecttype_from
	 */
	public final void setXpathReference_MxObjectType_From(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType xpathreference_mxobjecttype_from)
	{
		if (xpathreference_mxobjecttype_from == null)
			getMendixObject().setValue(context, MemberNames.XpathReference_MxObjectType_From.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.XpathReference_MxObjectType_From.toString(), xpathreference_mxobjecttype_from.getMendixObject().getId());
	}

	/**
	 * @return value of XpathReference_MxObjectType_To
	 */
	public final mxmodelreflection.proxies.MxObjectType getXpathReference_MxObjectType_To() throws com.mendix.core.CoreException
	{
		return getXpathReference_MxObjectType_To(getContext());
	}

	/**
	 * @param context
	 * @return value of XpathReference_MxObjectType_To
	 */
	public final mxmodelreflection.proxies.MxObjectType getXpathReference_MxObjectType_To(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.XpathReference_MxObjectType_To.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of XpathReference_MxObjectType_To
	 * @param xpathreference_mxobjecttype_to
	 */
	public final void setXpathReference_MxObjectType_To(mxmodelreflection.proxies.MxObjectType xpathreference_mxobjecttype_to)
	{
		setXpathReference_MxObjectType_To(getContext(), xpathreference_mxobjecttype_to);
	}

	/**
	 * Set value of XpathReference_MxObjectType_To
	 * @param context
	 * @param xpathreference_mxobjecttype_to
	 */
	public final void setXpathReference_MxObjectType_To(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType xpathreference_mxobjecttype_to)
	{
		if (xpathreference_mxobjecttype_to == null)
			getMendixObject().setValue(context, MemberNames.XpathReference_MxObjectType_To.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.XpathReference_MxObjectType_To.toString(), xpathreference_mxobjecttype_to.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return xpathReferenceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datatablesutils.proxies.XpathReference that = (datatablesutils.proxies.XpathReference) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DataTablesUtils.XpathReference";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
