// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datatablesutils.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DataTablesUtils module

	public static java.lang.String getLOGNODE_DATATABLES_UTILS()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DataTablesUtils.LOGNODE_DATATABLES_UTILS");
	}
}