// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datatablestestmodule.proxies;

public enum Gender
{
	Male(new java.lang.String[][] { new java.lang.String[] { "en_US", "Male" }, new java.lang.String[] { "nl_NL", "Man" } }),
	Female(new java.lang.String[][] { new java.lang.String[] { "en_US", "Female" }, new java.lang.String[] { "nl_NL", "Vrouw" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Gender(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
