// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package datatablesexportdata.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import datatablesexportdata.ExportDataImpl;
import datatablesexportdata.proxies.DataTablesExportDocument;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Generic function to export the data in a DataTables widget as downloadable file.
 */
public class ExportData extends CustomJavaAction<IMendixObject>
{
	private String configData;
	private String xpathConstraint;

	public ExportData(IContext context, String configData, String xpathConstraint)
	{
		super(context);
		this.configData = configData;
		this.xpathConstraint = xpathConstraint;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		final DataTablesExportDocument exportDocument = new ExportDataImpl(getContext()).export(configData, xpathConstraint);
		if (exportDocument != null) {
			return exportDocument.getMendixObject();
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ExportData";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
