// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datatablesexportdata.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DataTablesExportData module

	public static java.lang.String getLOGNODE_DATATABLES_EXPORT()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DataTablesExportData.LOGNODE_DATATABLES_EXPORT");
	}
}