// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datatablestestmodule.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DataTablesTestModule module

	public static String getLOG_NODE()
	{
		return (String)Core.getConfiguration().getConstantValue("DataTablesTestModule.LOG_NODE");
	}
}