// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datatablestestmodule.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DataTablesTestModule module

	public static java.lang.String getLOGNODE_DATATABLES_TEST()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DataTablesTestModule.LOGNODE_DATATABLES_TEST");
	}
}