// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datatablesutils.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the DataTablesUtils module
	public static void aCT_DataTablesExportData(IContext context, datatablestestmodule.proxies.DataTableContextEntity _dataTableContextEntity)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DataTableContextEntity", _dataTableContextEntity == null ? null : _dataTableContextEntity.getMendixObject());
			Core.execute(context, "DataTablesUtils.ACT_DataTablesExportData", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_DataTablesView_NewXpathSubView(IContext context, datatablesutils.proxies.DataTablesView _dataTablesView)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DataTablesView", _dataTablesView == null ? null : _dataTablesView.getMendixObject());
			Core.execute(context, "DataTablesUtils.ACT_DataTablesView_NewXpathSubView", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_DataTablesView_SaveNew(IContext context, datatablesutils.proxies.DataTablesView _dataTablesView)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DataTablesView", _dataTablesView == null ? null : _dataTablesView.getMendixObject());
			Core.execute(context, "DataTablesUtils.ACT_DataTablesView_SaveNew", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_DataTablesView_Validate(IContext context, datatablesutils.proxies.DataTablesView _view)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("View", _view == null ? null : _view.getMendixObject());
			Core.execute(context, "DataTablesUtils.ACT_DataTablesView_Validate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_XpathSubView_Save(IContext context, datatablesutils.proxies.XpathSubView _xpathSubView)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("XpathSubView", _xpathSubView == null ? null : _xpathSubView.getMendixObject());
			Core.execute(context, "DataTablesUtils.ACT_XpathSubView_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean aSU_DataTables(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "DataTablesUtils.ASU_DataTables", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mT_DataTablesView_CheckViews(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "DataTablesUtils.MT_DataTablesView_CheckViews", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_DataTablesView_MxObjectType(IContext context, datatablesutils.proxies.DataTablesView _dataTablesView)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DataTablesView", _dataTablesView == null ? null : _dataTablesView.getMendixObject());
			Core.execute(context, "DataTablesUtils.OCh_DataTablesView_MxObjectType", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_XpathReference_MxObjectReference(IContext context, datatablesutils.proxies.XpathReference _xpathReference)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("XpathReference", _xpathReference == null ? null : _xpathReference.getMendixObject());
			Core.execute(context, "DataTablesUtils.OCh_XpathReference_MxObjectReference", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_DataTablesView_Validate(IContext context, datatablesutils.proxies.DataTablesView _view)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("View", _view == null ? null : _view.getMendixObject());
			Core.execute(context, "DataTablesUtils.SUB_DataTablesView_Validate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sUB_XpathReference_Validate(IContext context, datatablesutils.proxies.XpathReference _xpathReference)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("XpathReference", _xpathReference == null ? null : _xpathReference.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "DataTablesUtils.SUB_XpathReference_Validate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sUB_XpathSubView_Validate(IContext context, datatablesutils.proxies.XpathSubView _xpathSubView, datatablesutils.proxies.XpathReference _xpathReference)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("XpathSubView", _xpathSubView == null ? null : _xpathSubView.getMendixObject());
			params.put("XpathReference", _xpathReference == null ? null : _xpathReference.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "DataTablesUtils.SUB_XpathSubView_Validate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}